<main class=pilule>
    <?php
        $choice = isset($_GET['choice']) ? (string) $_GET['choice'] : '0';;
        $sub2_1_2_2_2_init = 0;   

        if (strpos($choice, '2-1-2-2-2-7-4') === 0) 
        {
            $sub2_1_2_2_2_init = 1;
            require "templates/partials/choix_2/choix_2-1/choix_2-1-2/choix_2-1-2-2/choix_2-1-2-2-2/choix_bleu/finBleue.phtml";
        } 
        else if (strpos($choice, '2-1-2-2-2-7-5') === 0) 
        {
            $sub2_1_2_2_2_init = 1;
            require "templates/partials/choix_2/choix_2-1/choix_2-1-2/choix_2-1-2-2/choix_2-1-2-2-2/choix_rouge/finRouge.phtml";
        }

        if ($sub2_1_2_2_2_init === 0) 
        {
            echo '<p>Vous devez choisir entre la pilule Bleue ou la Pilule Rouge</p>';
            echo "<p>Choisis la pilule bleue et tout s'arrête, après tu pourras faire de beaux rêves et penser ce que tu veux.</p>";
            echo '<p>Choisis la pilule rouge : tu restes au Pays des Merveilles et on descend avec le lapin blanc au fond du gouffre </p>';
            echo '<a href="index.php?choice=2-1-2-2-2-7-4" class=bleue>Pilule Bleue<br></a>';
            echo '<a href="index.php?choice=2-1-2-2-2-7-5" class=rouge>Pilule Rouge</a>';
        }
    ?>
</main>